import chroma from 'chroma-js'

const theme = {
  foreground: '#1E2128',
  primary: '#1467C6',
  function: '#95262D',
  property: '#3A448C',
  variable: '#2E333D',
  keyword: '#B0187A',
  tag: '#5A7449',
  string: '#3D382E',
  builtin: '#346D91',
  comment: '#77858E',
}

function changeColorToHexAlphas(obj) {
  if (typeof obj === 'object') {
    for (var keys in obj) {
      if (typeof obj[keys] === 'object') {
        changeColorToHexAlphas(obj[keys])
      } else {
        let keyValue = obj[keys]
        if (chroma.valid(keyValue)) {
          obj[keys] = chroma(keyValue).hex()
        }
      }
    }
  }
  return obj
}

export default function getTheme() {
  const colors = changeColorToHexAlphas(theme)

  return {
    name: 'Mountains and Rivers',
    type: 'light',
    semanticHighlighting: true,
    semanticTokenColors: {
      function: colors.function,
      property: colors.property,
      variable: colors.variable,
    },
    colors: {
      focusBorder: colors.primary,
      foreground: '#616161',
      'selection.background': '#dde9f5',
      'scrollbar.shadow': '#beae9d',
      'activityBar.foreground': '#252525',
      'activityBar.background': '#ebeae6',
      'activityBar.border': '#dad9d5',
      'activityBar.inactiveForeground': '#515151e1',
      'activityBarBadge.foreground': '#ffffff',
      'activityBarBadge.background': colors.primary,
      'sideBar.background': '#ebeae6',
      'sideBar.foreground': '#616161',
      'sideBarSectionHeader.background': '#00000000',
      'sideBarSectionHeader.foreground': '#616161',
      'sideBarSectionHeader.border': '#61616130',
      'sideBarTitle.foreground': '#6f6f6f',
      'list.inactiveSelectionBackground': '#eeeeee',
      'list.inactiveSelectionForeground': '#616161',
      'list.hoverBackground': '#e8e8e8',
      'list.hoverForeground': '#616161',
      'list.activeSelectionBackground': '#00000044',
      'list.activeSelectionForeground': '#ffffff',
      'tree.indentGuidesStroke': '#a9a9a9',
      'list.dropBackground': '#f9f9f9',
      'list.highlightForeground': '#0066bf',
      'list.focusBackground': '#d6ebff',
      'list.focusForeground': '#616161',
      'listFilterWidget.background': '#efc1ad',
      'listFilterWidget.outline': '#00000000',
      'listFilterWidget.noMatchesOutline': '#be1100',
      'statusBar.foreground': '#252525',
      'statusBar.background': '#ebeae6',
      'statusBar.border': '#dad9d5',
      'statusBarItem.hoverBackground': '#ffffff1f',
      'statusBar.debuggingBackground': '#cc6633',
      'statusBar.debuggingForeground': '#ffffff',
      'statusBar.noFolderBackground': '#68217a',
      'statusBar.noFolderForeground': '#ffffff',
      'statusBarItem.remoteBackground': colors.primary,
      'statusBarItem.remoteForeground': '#ffffff',
      'titleBar.activeBackground': '#dddddd',
      'titleBar.activeForeground': '#333333',
      'titleBar.inactiveBackground': '#dddddd99',
      'titleBar.inactiveForeground': '#33333399',
      'titleBar.border': '#00000000',
      'menubar.selectionForeground': '#333333',
      'menubar.selectionBackground': '#0000001a',
      'menu.foreground': '#616161',
      'menu.background': '#ffffff',
      'menu.selectionForeground': '#ffffff',
      'menu.selectionBackground': '#0060c0',
      'menu.selectionBorder': '#00000000',
      'menu.separatorBackground': '#888888',
      'menu.border': '#00000085',
      'button.background': colors.primary,
      'button.foreground': '#ffffff',
      'button.hoverBackground': '#25526f',
      'button.secondaryForeground': '#ffffff',
      'button.secondaryBackground': '#5f6a79',
      'button.secondaryHoverBackground': '#4c5561',
      'input.background': '#ffffff',
      'input.border': '#00000000',
      'input.foreground': '#616161',
      'inputOption.activeBackground': '#0090f133',
      'inputOption.activeBorder': '#007acc00',
      'inputOption.activeForeground': '#000000',
      'input.placeholderForeground': '#767676',
      'textLink.foreground': '#006ab1',
      'editor.background': '#F8F6F5',
      'editor.foreground': colors.foreground,
      'editorLineNumber.foreground': '#237893',
      'editorCursor.foreground': '#cbb99d',
      'editorCursor.background': '#454545',
      'editor.selectionBackground': '#e2e8ee',
      'editor.inactiveSelectionBackground': '#e5ebf1',
      'editorWhitespace.foreground': '#33333333',
      'editor.selectionHighlightBackground': '#cbddff80',
      'editor.selectionHighlightBorder': '#495f7704',
      'editor.findMatchBackground': '#736d6666',
      'editor.findMatchBorder': '#00000010',
      'editor.findMatchHighlightBackground': '#ea5c0055',
      'editor.findMatchHighlightBorder': '#ffffff00',
      'editor.findRangeHighlightBackground': '#b4b4b44d',
      'editor.findRangeHighlightBorder': '#ffffff00',
      'editor.rangeHighlightBackground': '#fdff0033',
      'editor.rangeHighlightBorder': '#ffffff00',
      'editor.hoverHighlightBackground': '#add6ff26',
      'editor.wordHighlightStrongBackground': '#0e639c40',
      'editor.wordHighlightBackground': '#57575740',
      'editor.lineHighlightBackground': '#ffffff0A',
      'editor.lineHighlightBorder': '#eeeeee',
      'editorLineNumber.activeForeground': '#0b216f',
      'editorLink.activeForeground': '#0000ff',
      'editorIndentGuide.background': '#d3d3d3',
      'editorIndentGuide.activeBackground': '#a9aaab',
      'editorRuler.foreground': '#d3d3d3',
      'editorBracketMatch.background': '#0064001a',
      'editorBracketMatch.border': '#b9b9b9',
      'editor.foldBackground': '#add6ff4d',
      'editorOverviewRuler.background': '#25252500',
      'editorOverviewRuler.border': '#7f7f7f4d',
      'editorError.foreground': '#e51400',
      'editorError.background': '#B73A3400',
      'editorError.border': '#ffffff00',
      'editorWarning.foreground': '#e9a700',
      'editorWarning.background': '#A9904000',
      'editorWarning.border': '#ffffff00',
      'editorInfo.foreground': '#75beff',
      'editorInfo.background': '#4490BF00',
      'editorInfo.border': '#4490BF00',
      'editorGutter.background': '#f4f3f2',
      'editorGutter.modifiedBackground': '#66afe0',
      'editorGutter.addedBackground': '#81b88b',
      'editorGutter.deletedBackground': '#ca4b51',
      'editorGutter.foldingControlForeground': '#424242',
      'editorCodeLens.foreground': '#999999',
      'editorGroup.border': '#e7e7e7',
      'diffEditor.insertedTextBackground': '#9bb95533',
      'diffEditor.removedTextBackground': '#f5898933',
      'diffEditor.border': '#d7d7d7',
      'panel.background': '#f2f2ed',
      'panel.border': '#80808059',
      'panelTitle.activeBorder': '#424242',
      'panelTitle.activeForeground': '#424242',
      'panelTitle.inactiveForeground': '#424242bf',
      'badge.background': '#c4c4c4',
      'badge.foreground': '#333333',
      'terminal.foreground': '#333333',
      'terminal.selectionBackground': '#00000040',
      'terminalCursor.background': '#fcfeff',
      'terminalCursor.foreground': '#5a5a52',
      'terminal.border': '#80808059',
      'terminal.ansiBlack': '#000000',
      'terminal.ansiBlue': '#0451a5',
      'terminal.ansiBrightBlack': '#666666',
      'terminal.ansiBrightBlue': '#0451a5',
      'terminal.ansiBrightCyan': '#0598bc',
      'terminal.ansiBrightGreen': '#14ce14',
      'terminal.ansiBrightMagenta': '#bc05bc',
      'terminal.ansiBrightRed': '#cd3131',
      'terminal.ansiBrightWhite': '#a5a5a5',
      'terminal.ansiBrightYellow': '#b5ba00',
      'terminal.ansiCyan': '#0598bc',
      'terminal.ansiGreen': '#00bc00',
      'terminal.ansiMagenta': '#bc05bc',
      'terminal.ansiRed': '#cd3131',
      'terminal.ansiWhite': '#555555',
      'terminal.ansiYellow': '#949800',
      'breadcrumb.background': '#f4f3f2',
      'breadcrumb.foreground': '#616161cc',
      'breadcrumb.focusForeground': '#4e4e4e',
      'editorGroupHeader.tabsBackground': '#f3f3f3',
      'tab.activeForeground': '#333333',
      'tab.border': '#a1a1a13e',
      'tab.activeBackground': '#f4f3f2',
      'tab.activeBorder': '#00000000',
      'tab.activeBorderTop': '#00000000',
      'tab.inactiveBackground': '#e4e3df',
      'tab.inactiveForeground': '#333333b3',
      'scrollbarSlider.background': '#64646444',
      'scrollbarSlider.hoverBackground': '#6464647a',
      'scrollbarSlider.activeBackground': '#0000006a',
      'progressBar.background': colors.primary,
      'widget.shadow': '#00000029',
      'editorWidget.foreground': '#616161',
      'editorWidget.background': '#f3f3f3',
      'editorWidget.resizeBorder': '#c7c7c7',
      'pickerGroup.border': '#cccedb',
      'pickerGroup.foreground': colors.primary,
      'debugToolBar.background': '#f3f3f3',
      'debugToolBar.border': '#d5d5d5',
      'notifications.foreground': '#616161',
      'notifications.background': '#f3f3f3',
      'notificationToast.border': '#d5d5d5',
      'notificationsErrorIcon.foreground': '#e51400',
      'notificationsWarningIcon.foreground': '#e9a700',
      'notificationsInfoIcon.foreground': '#75beff',
      'notificationCenter.border': '#d5d5d5',
      'notificationCenterHeader.foreground': '#616161',
      'notificationCenterHeader.background': '#e7e7e7',
      'notifications.border': '#e7e7e7',
      'gitDecoration.addedResourceForeground': '#587c0c',
      'gitDecoration.conflictingResourceForeground': '#6c6cc4',
      'gitDecoration.deletedResourceForeground': '#ad0707',
      'gitDecoration.ignoredResourceForeground': '#8e8e90',
      'gitDecoration.modifiedResourceForeground': '#895503',
      'gitDecoration.stageDeletedResourceForeground': '#ad0707',
      'gitDecoration.stageModifiedResourceForeground': '#895503',
      'gitDecoration.submoduleResourceForeground': '#1258a7',
      'gitDecoration.untrackedResourceForeground': '#007100',
      'editorMarkerNavigation.background': '#ffffff',
      'editorMarkerNavigationError.background': '#e51400',
      'editorMarkerNavigationWarning.background': '#e9a700',
      'editorMarkerNavigationInfo.background': '#75beff',
      'merge.currentHeaderBackground': '#A4E3D6',
      'merge.currentContentBackground': '#DBF4EF',
      'merge.incomingHeaderBackground': '#A6CFFF',
      'merge.incomingContentBackground': '#DBECFF',
      'merge.commonHeaderBackground': '#BFBFBF',
      'merge.commonContentBackground': '#E5E5E5',
      'editorSuggestWidget.background': '#e7e7e5',
      'editorSuggestWidget.border': '#c8c8c8',
      'editorSuggestWidget.foreground': '#4f4f4f',
      'editorSuggestWidget.highlightForeground': '#3b3b3b',
      'editorSuggestWidget.selectedBackground': '#64788d',
      'editorSuggestWidget.focusHighlightForeground': '#ffffff',
      'editorSuggestWidget.selectedForeground': '#d2dde8',
      'editorHoverWidget.foreground': '#616161',
      'editorHoverWidget.background': '#f3f3f3',
      'editorHoverWidget.border': '#c8c8c8',
      'peekView.border': '#007acc',
      'peekViewEditor.background': '#f2f8fc',
      'peekViewEditorGutter.background': '#f2f8fc',
      'peekViewEditor.matchHighlightBackground': '#f5d802de',
      'peekViewEditor.matchHighlightBorder': '#dbc417',
      'peekViewResult.background': '#f3f3f3',
      'peekViewResult.fileForeground': '#1e1e1e',
      'peekViewResult.lineForeground': '#646465',
      'peekViewResult.matchHighlightBackground': '#ea5c004d',
      'peekViewResult.selectionBackground': '#3399ff33',
      'peekViewResult.selectionForeground': '#6c6c6c',
      'peekViewTitle.background': '#ffffff',
      'peekViewTitleDescription.foreground': '#616161e6',
      'peekViewTitleLabel.foreground': '#333333',
      'icon.foreground': '#616161',
      'checkbox.background': '#ffffff',
      'checkbox.foreground': '#616161',
      'checkbox.border': '#00000000',
      'dropdown.background': '#ffffff',
      'dropdown.foreground': '#616161',
      'dropdown.border': '#00000000',
      'minimapGutter.addedBackground': '#81b88b',
      'minimapGutter.modifiedBackground': '#66afe0',
      'minimapGutter.deletedBackground': '#ca4b51',
      'minimap.findMatchHighlight': '#736d6666',
      'minimap.selectionHighlight': '#e2e8ee',
      'minimap.errorHighlight': '#e51400',
      'minimap.warningHighlight': '#e9a700',
      'minimap.background': '#f4f3f2',
      'sideBar.dropBackground': '#f9f9f9',
      'editorGroup.emptyBackground': '#f4f3f2',
      'panelSection.border': '#80808059',
      'statusBarItem.activeBackground': '#FFFFFF25',
      'settings.headerForeground': '#616161',
      'settings.focusedRowBackground': '#ffffff07',
      'walkThrough.embeddedEditorBackground': '#00000050',
      'breadcrumb.activeSelectionForeground': '#4e4e4e',
      'editorGutter.commentRangeForeground': '#424242',
      'debugExceptionWidget.background': '#f3f3f3',
      'debugExceptionWidget.border': '#d5d5d5',
      'editorBracketHighlight.foreground1': '#b84778',
      'editorBracketHighlight.foreground2': '#78b847',
      'editorBracketHighlight.foreground3': '#4778b8',
      'editorBracketHighlight.foreground4': '#b84778',
      'editorBracketHighlight.foreground5': '#78b847',
      'editorBracketHighlight.foreground6': '#4778b8',
    },
    tokenColors: [
      {
        scope: [
          'string',
          'string punctuation.section.embedded source',
          'attribute.value',
          'string.regexp.character-class',
          'string.regexp constant.character.escape',
          'string.regexp source.ruby.embedded',
          'string.regexp string.regexp.arbitrary-repitition',
        ],
        settings: {
          foreground: colors.string,
        },
      },
      {
        scope: [
          'property',
          'meta.property-name',
          'meta.object-literal.key',
          'attribute.name',
          'variable.other.property',
          'entity.other.attribute-name',
          'invalid.deprecated.entity.other.attribute-name.html',
        ],
        settings: {
          foreground: colors.property,
        },
      },
      {
        scope: ['keyword'],
        settings: {
          foreground: colors.keyword,
        },
      },
      {
        scope: ['entity.name.tag', 'support.type.property-name'],
        settings: {
          foreground: colors.tag,
        },
      },
      {
        scope: [
          'storage',
          'storage.type',
          'support.type.builtin',
          'constant.language.undefined',
          'constant.language.null',
        ],
        settings: {
          foreground: colors.builtin,
        },
      },
      {
        scope: ['support.class'],
        settings: {
          foreground: colors.function,
        },
      },
      {
        scope: ['comment', 'punctuation.definition.comment', 'string.comment'],
        settings: {
          foreground: colors.comment,
        },
      },
    ],
  }
}
